nodeLinker: pnp

npmRegistries:
  //git.teko.vn/api/v4/projects/2217/packages/npm:
    npmAlwaysAuth: true

npmScopes:
  tempi:
    npmAlwaysAuth: true
    npmRegistryServer: "https://git.teko.vn/api/v4/projects/2217/packages/npm"

pnpMode: loose